# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a5YuNFqLSQkX3Nt7IdS6oHY-EcCBHwFF
"""

import pandas as pd

def get_summary(string):
  summary=wikipedia.summary(string)
  summary = re.sub(r"^$.\n" ,"\n",summary)
  summary = summary.replace("\'s","'s")
  summary = summary.replace('\xa0','')
  summary = re.sub(r'\n+', "\n", summary)
  summary = re.sub(r"[\([{'?\})\]]", "", summary)
  text = re.sub("[\a-zA-Z]+", " ",summary)

  return text

def get_content(string):
  wiki = wikipedia.page(string)
  text = wiki.content
  text = re.sub(r'==.*?==+', '', text)
  text = text.replace('\n', '.')
  text = re.sub(r'\.+', ".", text)
  text = re.sub(r"[\([{'?\})\]]", "", text)
  text = re.sub("[\a-zA-Z]+", " ",text)

  return text